Update README to include version on python.
% pip install -r requirements.txt
Traceback (most recent call last):
  File "/Users/ray/Library/Python/3.7/bin/pip", line 6, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip._internal.cli.main'

Thus I see that the 3.7 version of python is required.